spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?useSSL=false&characterEncoding=utf-8
    username: root
    password: "000411"
    driver-class-name: com.mysql.cj.jdbc.Driver
  # RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        auto-startup: true
      direct:
        retry:
          enabled: true



mybatis:
  #对应mapper映射xml文件所在的路径
  mapper-locations: classpath:mapper/*.xml
  #对应实体类的路径
  type-aliases-package: group.uchain.panghu.entity

#jwt
jwt:
  secret: swpu-uchain
  expiration: 1296000

filepath:
  project-excel: /home/panghu/IdeaProjects/Project_Management_System/src/main/resources/file/
  register-excel: /home/panghu/IdeaProjects/Project_Management_System/src/main/resources/file2/


default:
  password: 123456