spring:
  mvc:
    view:
      prefix: /
      suffix: .html
  datasource:
    url: jdbc:mysql://47.107.61.232:3306/project?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: "000411@Dgh"
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Redis
  redis:
    port: 6380
    host: 127.0.0.1
    password: "000411"
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        min-idle: 0
        max-idle: 8
  # RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        auto-startup: true
      direct:
        retry:
          enabled: true



mybatis:
  #对应mapper映射xml文件所在的路径
  mapper-locations: classpath:mapper/*.xml
  #对应实体类的路径
  type-aliases-package: group.uchain.project.form



#jwt
jwt:
  secret: swpu-uchain
  expiration: 86400

filepath:
  project-excel: /root/home/panghu/Project/project/register-excel/
  register-excel: /root/home/panghu/Project/project/project-info-excel/
  evident: /root/home/panghu/Project/project/evident/

file:
  zip-name: files.zip

default:
  password: 123456